# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:

    # Orderer Organization
    - &MainOrgOrderer
        # MainOrderer Membership Service Provider
        Name: MainOrgOrdererMSP

        # ID to load the MSP definition as
        ID: MainOrgOrdererMSP

        # MSPDir is the filesystem path which contains the MSP configuration
        MSPDir: crypto-config/ordererOrganizations/orderer.com/msp

        AdminPrincipal: Role.ADMIN

    # Main Organization (Network Core)
    - &MainOrg
        # Main Organization Membership Service Provider
        Name: MainOrgMSP

        # ID to load the MSP definition as
        ID: MainOrgMSP

        MSPDir: crypto-config/peerOrganizations/main.org.com/msp

        AdminPrincipal: Role.ADMIN

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.main.org.com
              Port: 7051

    # Sample Org, ID1
    - &Org1
        # Sample Org ID1, MSP
        Name: Org1MSP

        # ID to load the MSP definition as
        ID: Org1MSP

        MSPDir: crypto-config/peerOrganizations/org1.org.com/msp

        AdminPrincipal: Role.MEMBER

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org1.org.com
              Port: 7051

    # Sample Org, ID2
    - &Org2
        # Sample Org ID2, MSP
        Name: Org2MSP

        # ID to load the MSP definition as
        ID: Org2MSP

        MSPDir: crypto-config/peerOrganizations/org2.org.com/msp

        AdminPrincipal: Role.MEMBER

        AnchorPeers:
            # AnchorPeers defines the location of peers which can be used
            # for cross org gossip communication.  Note, this value is only
            # encoded in the genesis block in the Application section context
            - Host: peer0.org2.org.com
              Port: 7051


################################################################################
#
#   SECTION: Orderer
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for orderer related parameters
#
################################################################################
Orderer: &OrdererDefaults

    # Orderer Type: The orderer implementation to start
    # Available types are "solo" and "kafka"
    OrdererType: solo

    Addresses:
        - orderer0.orderer.com:7050

    # Batch Timeout: The amount of time to wait before creating a batch
    BatchTimeout: 2s

    # Batch Size: Controls the number of messages batched into a block
    BatchSize:

        # Max Message Count: The maximum number of messages to permit in a batch
        MaxMessageCount: 10

        # Absolute Max Bytes: The absolute maximum number of bytes allowed for
        # the serialized messages in a batch.
        AbsoluteMaxBytes: 99 MB

        # Preferred Max Bytes: The preferred maximum number of bytes allowed for
        # the serialized messages in a batch. A message larger than the preferred
        # max bytes will result in a batch larger than preferred max bytes.
        PreferredMaxBytes: 512 KB

    Kafka:
        # Brokers: A list of Kafka brokers to which the orderer connects
        # NOTE: Use IP:port notation
        Brokers:
            - kafka0:9092
            - kafka1:9092
            - kafka2:9092
            - kafka3:9092
    # Organizations is the list of orgs which are defined as participants on
    # the orderer side of the network
    Organizations:

################################################################################
#
#   SECTION: Application
#
#   - This section defines the values to encode into a config transaction or
#   genesis block for application related parameters
#
################################################################################
Application: &ApplicationDefaults

    # Organizations is the list of orgs which are defined as participants on
    # the application side of the network
    Organizations:

################################################################################
#
#   CAPABILITIES
#
#   This section defines the capabilities of fabric network. This is a new
#   concept as of v1.1.0 and should not be utilized in mixed networks with
#   v1.0.x peers and orderers.  Capabilities define features which must be
#   present in a fabric binary for that binary to safely participate in the
#   fabric network.  For instance, if a new MSP type is added, newer binaries
#   might recognize and validate the signatures from this type, while older
#   binaries without this support would be unable to validate those
#   transactions.  This could lead to different versions of the fabric binaries
#   having different world states.  Instead, defining a capability for a channel
#   informs those binaries without this capability that they must cease
#   processing transactions until they have been upgraded.  For v1.0.x if any
#   capabilities are defined (including a map with all capabilities turned off)
#   then the v1.0.x peer will deliberately crash.
#
################################################################################
Capabilities:
    # Channel capabilities apply to both the orderers and the peers and must be
    # supported by both.  Set the value of the capability to true to require it.
    Global: &ChannelCapabilities
        V1_3: true
        # (V1_2 not defined in fabric)
        # Note: older ones are superceded, e.g. V1_3 capabilities include V1_1.
        # Thus, those like V1_1 need not be set if V1_3 or later is set true.
        # But keep them, to allow disabling V1_3 when bringing up a new test
        # network, if desired, possibly in anticipation of an upgrade test.
        V1_1: true

    # Orderer capabilities apply only to the orderers, and may be safely
    # manipulated without concern for upgrading peers.  Set the value of the
    # capability to true to require it.
    Orderer: &OrdererCapabilities
        # (V1_3 not defined in fabric)
        # (V1_2 not defined in fabric)
        V1_1: true

    # Application capabilities apply only to the peer network, and may be safely
    # manipulated without concern for upgrading orderers.  Set the value of the
    # capability to true to require it.
    Application: &ApplicationCapabilities
        V1_3: true
        V1_2: true
        # Note: older ones are superceded, e.g. V1_2 capabilities include V1_1.
        # Thus, older ones like V1_1 need not be set if we set V1_2 or later.
        # But keep them all; that would allow tester to override and disable
        # newer ones like Capabilities.Global.V1_3 and
        # Capabilities.Application.V1_3 when bringing up a new test network,
        # if desired, possibly in anticipation of an upgrade test.
        V1_1: true


################################################################################
#
#   Profile
#
#   - Different configuration profiles may be encoded here to be specified
#   as parameters to the configtxgen tool
#
################################################################################
Profiles:

    MainOrgGenesis:
        Capabilities:
            <<: *ChannelCapabilities
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *MainOrgOrderer
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            MainOrgConsortium:
                Organizations:
                    - *MainOrg
                    - *Org1
                    - *Org2
    MainOrgChannel:
        Capabilities:
            <<: *ChannelCapabilities
        Consortium: MainOrgConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *MainOrg
        Capabilities:
            <<: *ApplicationCapabilities
    AllOrgsChannel:
        Capabilities:
            <<: *ChannelCapabilities
        Consortium: MainOrgConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *MainOrg
                - *Org1
                - *Org2
        Capabilities:
            <<: *ApplicationCapabilities

