# ---------------------------------------------------------------------------
# "OrdererOrgs" - Definition of organizations managing orderer nodes
# ---------------------------------------------------------------------------
#OrdererOrgs:
#  # ---------------------------------------------------------------------------
#  # Orderer
#  # ---------------------------------------------------------------------------
#  - Name: MainOrgOrderer
#    Domain: orderer.com
#    # ---------------------------------------------------------------------------
#    # "Specs" - See PeerOrgs below for complete description
#    # ---------------------------------------------------------------------------
#    #Specs:
#    #  - Hostname: mainorgorderer
#    Template:
#      Count: 3

# ---------------------------------------------------------------------------
# "PeerOrgs" - Definition of organizations managing peer nodes
# ---------------------------------------------------------------------------
PeerOrgs:
  # ---------------------------------------------------------------------------
  # MainOrg
  # ---------------------------------------------------------------------------
  - Name: MainOrg
    Domain: main.org.com
    EnableNodeOUs: true
    # ---------------------------------------------------------------------------
    # "Specs"
    # ---------------------------------------------------------------------------
    # Uncomment this section to enable the explicit definition of hosts in your
    # configuration.  Most users will want to use Template, below
    #
    # Specs is an array of Spec entries.  Each Spec entry consists of two fields:
    #   - Hostname:   (Required) The desired hostname, sans the domain.
    #   - CommonName: (Optional) Specifies the template or explicit override for
    #                 the CN.  By default, this is the template:
    #
    #                              "{{.Hostname}}.{{.Domain}}"
    #
    #                 which obtains its values from the Spec.Hostname and
    #                 Org.Domain, respectively.
    #   - SANS:       (Optional) Specifies one or more Subject Alternative Names
    #                 the be set in the resulting x509.  Accepts template
    #                 variables {{.Hostname}}, {{.Domain}}, {{.CommonName}}
    #                 NOTE: Two implicit entries are created for you:
    #                     - {{ .CommonName }}
    #                     - {{ .Hostname }}
    Specs:
      - Hostname: peer0 # implicitly "peer0.main.org.com"
        SANS:
          - "localhost"
      - Hostname: peer1 # implicitly "peer1.main.org.com"
        SANS:
          - "localhost"
      - Hostname: orderer0 # implicitly "orderer0.main.org.com"
        SANS:
          - "localhost"
      - Hostname: orderer1 # implicitly "orderer1.main.org.com"
        SANS:
          - "localhost"
      - Hostname: orderer2 # implicitly "orderer2.main.org.com"
        SANS:
        - "localhost"

    # ---------------------------------------------------------------------------
    # "Template"
    # ---------------------------------------------------------------------------
    # Allows for the definition of 1 or more hosts that are created sequentially
    # from a template. By default, this looks like "peer%d" from 0 to Count-1.
    # You may override the number of nodes (Count), the starting index (Start)
    # or the template used to construct the name (Hostname).
    #
    # Note: Template and Specs are not mutually exclusive.  You may define both
    # sections and the aggregate nodes will be created for you.  Take care with
    # name collisions
    # ---------------------------------------------------------------------------
    #Template:
    #  Count: 2
    #  Start: 5
    #  Hostname: {{.Prefix}}{{.Index}} # default
    #  SANS:
    #    - "localhost"

    # ---------------------------------------------------------------------------
    # "Users"
    # ---------------------------------------------------------------------------
    # Count: The number of user accounts _in addition_ to Admin
    # ---------------------------------------------------------------------------
    Users:
      Count: 0

  # ---------------------------------------------------------------------------
  # Org1: See "MainOrg" for full specification
  # ---------------------------------------------------------------------------
  - Name: Org1
    Domain: org1.org.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0 # implicitly "peer0.org1.org.com"
        SANS:
        - "localhost"
      - Hostname: peer1 # implicitly "peer1.org1.org.com"
        SANS:
        - "localhost"
      - Hostname: orderer0 # implicitly "orderer0.org1.org.com"
        SANS:
        - "localhost"
      - Hostname: orderer1 # implicitly "orderer1.org1.org.com"
        SANS:
        - "localhost"
      - Hostname: orderer2 # implicitly "orderer2.org1.org.com"
        SANS:
        - "localhost"
    #Template:
    #  Count: 2
    Users:
      Count: 0

  # ---------------------------------------------------------------------------
  # Org2: See "MainOrg" for full specification
  # ---------------------------------------------------------------------------
  - Name: Org2
    Domain: org2.org.com
    EnableNodeOUs: true
    Specs:
      - Hostname: peer0 # implicitly "peer0.org2.org.com"
        SANS:
        - "localhost"
      - Hostname: peer1 # implicitly "peer1.org2.org.com"
        SANS:
        - "localhost"
      - Hostname: orderer0 # implicitly "orderer0.org2.org.com"
        SANS:
        - "localhost"
      - Hostname: orderer1 # implicitly "orderer1.org2.org.com"
        SANS:
        - "localhost"
      - Hostname: orderer2 # implicitly "orderer2.org2.org.com"
        SANS:
        - "localhost"
    #Template:
    #  Count: 2
    Users:
      Count: 0
